#!/usr/bin/php
<?php
   // shell_exec('yarn build');
    define('LOGIN', 'root');
    define('PASSW', 'Eifvfyf3herb');
    define('SERVER', 'podruzhki.pro');

    $connection = ssh2_connect(SERVER, 2308);
    ssh2_auth_password($connection, LOGIN, PASSW);

    ssh2_scp_send($connection, '/var/www/crm/youna.reviewapp/dist/umi.js', '/var/www/podruzhki.pro/static/review/app.js', 0755);
    sleep(1);
    ssh2_scp_send($connection, '/var/www/crm/youna.reviewapp/dist/umi.css', '/var/www/podruzhki.pro/static/review/app.css', 0755);
    sleep(1);
    ssh2_scp_send($connection, '/var/www/crm/youna.reviewapp/dist/umi.js', '/var/www/podruzhki.pro/static/review/app.js', 0755);


    echo "\nDone {youna.reviewapp}\n";
?>